added consistent name tag
cyberDanco/deployAWSVPC pull request #2
Opened 2022-06-19 02:46 UTC by cyberDanco

Added consistent name tag

2022-06-20 13:39 UTC, vladimirmukhin requested changes

2022-06-20 13:39 UTC, vladimirmukhin commented on main.tf
> +    #Name = "private${count.index}"
Please don't leave commented-out code blocks. That's considered a bad style.
Please fix it here and in all other parts of code that has similar issue

2022-06-20 13:39 UTC, vladimirmukhin commented on main.tf
> +variable "env_code" {
I see that you already have the environemnt_tag variable which is very similar.
We can re-use it instead of introducing a new one

2022-06-20 13:39 UTC, vladimirmukhin commented on main.tf
> +  tags = {
```suggestion
  vpc   = true
  
  tags = {
```

2022-06-23 00:34 UTC, cyberDan-dev commented on main.tf
> +  tags = {
Changes made and pushed based on comments above.

2022-06-23 01:44 UTC, vladimirmukhin approved these changes

2022-06-23 01:48 UTC, merged